language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token:
      secure: "gy3twDkaC0RZjGxRLS2uIq+gSTnSex7T5Hx4+ydpEs3NRqsUB9BU2WfO1qw5tZ3wMgKPYZDS1RHn1iox1CdgvJJoIKPUgoPp6trN3KRRSrYT4dhhyMposOsLa/1nJBW2w0OIhI7ZARqwgOuHZxBQCBqg1wy2EjEgwSjKMCyYWIUuzvAVfCkLwTpfMtfwVBeqXlMknxuLTJviPM+8GOUg/Ju208DmolcMNEEAHyhl6Nrj4azaZdcIz+PmMGr/+f0fiLpVovdqg5aEgkI8l/rZ41nE0MbEWIYsz/kj/13+jaaIBzsZGl4dnbNjT/nLwMsUIqjV9DJmal27oIzxORcGUWe47zXITLL9p+wsQFdLyPSEGz5dWUfmzIZRQd52xz0WtBDqGZcBKdWiVAIVBC06zEgIy/p9lozFYzLadW/CgWkn9BJq0EEy4iWN5NT5erMBdQsxTsXFRSVuOcT4ZaWKiZenCXc/a2sly+0Ovus4X4WyqwAQ7cs9lTyJb1OqQsW9MqkM9fS6yQXNecHefdDIkC1/BUXa1mzthKhiVYkbtx7UaYyTrijLmnzAYkpVDvKbT7dsAcSUIbAAXuWzo50mNeW+oAfEfOhftsC45KIXG6PmX9T5kt7i0xlGdC+7CI5v9Z3wmI1Ai/3km+bVG47DRnr62qhFq0DHIopmRCAYvvg="
